package net.flectone.pulse.util.constant;

public enum CacheName {

    ANIMATION,
    COOLDOWN,
    DIALOG_CLICK,
    OFFLINE_PLAYERS,
    MODERATION,
    ICU_MESSAGE,
    LEGACY_COLOR_MESSAGE,
    MENTION_MESSAGE,
    SWEAR_MESSAGE,
    REPLACEMENT_MESSAGE,
    REPLACEMENT_IMAGE,
    TRANSLATE_MESSAGE,
    PROFILE_PROPERTY,
    PLAYTIME,
    PLAYER_COLOR,
    PLAYER_SETTING,
    PLAYER_IGNORE

}
