modLoader="javafml"
loaderVersion="[1,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/Flectone/FlectonePulse/issues"

[[mods]]
modId="flectonepulse"
version="${version}"
displayName="FlectonePulse"
updateJSONURL="https://flectone.net/pulse/update.json"
displayURL="https://flectone.net/pulse/"
logoFile="icon.png"
credits="TheFaser"
authors="TheFaser"
description='''${description}'''

[[dependencies.flectonepulse]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="SERVER"

[[dependencies.flectonepulse]]
modId="minecraft"
type="required"
versionRange="[26.2,)"
ordering="NONE"
side="SERVER"

[[dependencies.flectonepulse]]
modId="packetevents"
type="required"
versionRange="[2.12.3,)"
ordering="AFTER"
side="SERVER"
