server: ""
version: "1.11.1-SNAPSHOT"
language:
  type: "en_us"
  by_player: true
database:
  ignore_existing_driver: false
  use_playtime_tracking: true
  type: "H2"
  name: "flectonepulse"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "1234"
  parameters: "?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8"
  prefix: ""
executor:
  min_pool_size: 0
  max_pool_size: -1
  work_queue: "SYNCHRONOUS"
  keep_alive:
    duration: 60
    time_unit: "SECONDS"
  shutdown_timeout:
    duration: 5
    time_unit: "SECONDS"
proxy:
  clusters: []
  bungeecord: false
  velocity: false
  redis:
    enable: false
    host: "127.0.0.1"
    port: 6379
    ssl: false
    user: ""
    password: ""
internal:
  enable: true
  always_send_silent_packet: false
  use_paper_message_sender: false
  use_packet_login_listener: false
  unregister_command_on_reload: false
  vanilla_commands_to_remove:
    - "msg"
    - "banlist"
    - "kick"
    - "w"
    - "tell"
    - "me"
    - "pardon"
    - "ban"
    - "whitelist"
logger:
  console: "Console"
  prefix: "(FlectonePulse) "
  description:
    - " ___       ___  __  ___  __        ___"
    - "|__  |    |__  /  `  |  /  \\ |\\ | |__"
    - "|    |___ |___ \\__,  |  \\__/ | \\| |___"
    - " __             __   ___"
    - "|__) |  | |    /__` |__ "
    - "|    \\__/ |___ .__/ |___   /\\"
    - "                          /  \\ v<version>"
    - "__/\\___  ____/\\_____  ___/    \\______"
    - "       \\/           \\/"
  primary: "\e[38;2;77;166;255m"
  warn: "\e[33m"
  info: "\e[38;2;166;216;255m"
  filter:
  - "Paper Async Command Builder"
  - "Caught previously unhandled exception :"
  - "Error received from Telegram GetUpdates Request"
  - "OkHttp TaskRunner"
  - "Exception in thread \"ForkJoinPool"
  - "FlectonePulseDatabase - "
cache:
  types:
    ANIMATION:
      invalidate_on_reload: true
      duration: 1
      time_unit: "MINUTES"
      size: 10000
    COOLDOWN:
      invalidate_on_reload: false
      duration: 5
      time_unit: "HOURS"
      size: 5000
    DIALOG_CLICK:
      invalidate_on_reload: false
      duration: 1
      time_unit: "SECONDS"
      size: 100
    OFFLINE_PLAYERS:
      invalidate_on_reload: false
      duration: 1
      time_unit: "HOURS"
      size: 1000
    MODERATION:
      invalidate_on_reload: false
      duration: 1
      time_unit: "HOURS"
      size: 5000
    ICU_MESSAGE:
      invalidate_on_reload: false
      duration: 10
      time_unit: "MINUTES"
      size: 100000
    LEGACY_COLOR_MESSAGE:
      invalidate_on_reload: false
      duration: 10
      time_unit: "MINUTES"
      size: 100000
    MENTION_MESSAGE:
      invalidate_on_reload: false
      duration: 10
      time_unit: "MINUTES"
      size: 1000
    SWEAR_MESSAGE:
      invalidate_on_reload: false
      duration: 10
      time_unit: "MINUTES"
      size: 100000
    REPLACEMENT_MESSAGE:
      invalidate_on_reload: false
      duration: 10
      time_unit: "MINUTES"
      size: 100000
    REPLACEMENT_IMAGE:
      invalidate_on_reload: false
      duration: 10
      time_unit: "MINUTES"
      size: 100
    TRANSLATE_MESSAGE:
      invalidate_on_reload: false
      duration: 1
      time_unit: "HOURS"
      size: 5000
    PROFILE_PROPERTY:
      invalidate_on_reload: false
      duration: 1
      time_unit: "HOURS"
      size: 1000
    PLAYTIME:
      invalidate_on_reload: true
      duration: 10
      time_unit: "MINUTES"
      size: 100
    PLAYER_COLOR:
      invalidate_on_reload: true
      duration: 10
      time_unit: "MINUTES"
      size: 1000
    PLAYER_SETTING:
      invalidate_on_reload: true
      duration: 10
      time_unit: "MINUTES"
      size: 1000
    PLAYER_IGNORE:
      invalidate_on_reload: true
      duration: 1
      time_unit: "HOURS"
      size: 1000
metrics:
  enable: true
